version: '3.8'
services:
  mis-container:
    image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    restart: always
    container_name: 'react'
    ports:
      - 8001:80
    networks:
      - elyas

networks:
  karama:
    name: elyas
    external: true
